### ISSUE TITLE
error: failed to select a version for the requirement `funty = "~1.2"`

### ISSUE THREAD

**Issue by yanyanho** [EDGDrummond/EF-grant#1]
Hi , can you help me fix the problem. It is the version problem of "https://github.com/privacy-scaling-explorations/halo2.git"

**Comment by yanyanho** [comment]
It seens the problem with "pairing = { git = "https://github.com/privacy-scaling-explorations/pairing", package = "pairing_bn256"}"

**Comment by vhjiang** [comment]
For new comers, the fix can be done by changing the line in Cargo.toml:

`pairing = { git = 'https://github.com/privacy-scaling-explorations/pairing.git', package = "pairing_bn256"}
`

to

`pairing = { git = 'https://github.com/vhjiang/pairing.git', package = "pairing_bn256"}
`

The difference is I upgraded ff dependency to `ff = "0.13"` in `pairing_bn256`.

**Comment by EDGDrummond** [comment]
Thanks for the suggested solution vhjiang. Additional dependencies caused more problems since this repo was made. All this has been fixed in commit fd2f462 (I forked the relevant repos myself so that this and those are managed by the same account)
