### ISSUE TITLE
cannot find derive macro `ConstParamTy` in this scope

### ISSUE THREAD

**Issue by Demian101** [EDGDrummond/EF-grant#4]
```
$ cargo criterion --bench ecdsa

    Skipping git submodule `https://github.com/ethereum/tests` due to update strategy in .gitmodules
    Skipping git submodule `https://github.com/OpenZeppelin/openzeppelin-contracts` due to update strategy in .gitmodules
   Compiling zkevm-circuits v0.1.0 (https://github.com/EDGDrummond/zkevm-circuits.git#d9fb3b82)
error: cannot find derive macro `ConstParamTy` in this scope
  --> /Users/soda/.cargo/git/checkouts/zkevm-circuits-e28bdf2295242332/d9fb3b8/zkevm-circuits/src/evm_circuit/step.rs:37:61
   |
37 | #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, EnumIter, ConstParamTy)]
   |                                                             ^^^^^^^^^^^^

error: could not compile `zkevm-circuits` due to previous error
Error: 'cargo bench' returned an error (exit status: 101); unable to continue.
```

<img width="998" alt="image" src="https://github.com/EDGDrummond/EF-grant/assets/33189338/7cd48e40-b381-43a2-b556-5fbb6686b88f">

----

About my rust version: 

```bash
active toolchain
----------------

nightly-2022-11-22-x86_64-apple-darwin (overridden by '/Users/soda/halo2/EF-grant-main/rust-toolchain')
rustc 1.67.0-nightly (b7bc90fea 2022-11-21)
```

any help thanks ~

**Comment by EDGDrummond** [comment]
Are you overriding the toolchain at all? The rust-toolchain file should provide the relevant rust version. When you run
```
rustup show
```

you should get this
<img width="767" alt="Screenshot 2023-10-31 at 14 05 22" src="https://github.com/EDGDrummond/EF-grant/assets/57955633/d97287c9-60a2-434b-8ba9-6d2279ebccd2">

If you are not seeing this rust version then you are on the wrong toolchain

**Comment by Demian101** [comment]
the same as yours ~ 🤣 

```
$ rustup show

active toolchain
----------------

nightly-2022-11-22-x86_64-apple-darwin (overridden by '/Users/soda/halo2/EF-grant-main/rust-toolchain')
rustc 1.67.0-nightly (b7bc90fea 2022-11-21)
```

**Comment by EDGDrummond** [comment]
Firstly sorry for being blind to the second half of your message 😅

That's very strange. Final sanity check - have you tried 
`cargo clean
cargo build`
then run the command again?

**Comment by Demian101** [comment]
Just now I tried , but no magic occur...

and my friend also meet this question.

> We both used the newest githun repo version.

<img width="953" alt="image" src="https://github.com/EDGDrummond/EF-grant/assets/33189338/f67e5320-48ec-4925-9057-280c26385826">

**Comment by EDGDrummond** [comment]
Let me spin up a new docker container and try again, it's hard to solve when I can't recreate the problem.

The newest commit is the one that fixed the breaking dependency changes aha

**Comment by Demian101** [comment]
thanks! 
If any further dependencies/environment info needed , pls let me know ~

**Comment by EDGDrummond** [comment]
I removed ConstParamTy from that dependency and point to that specific commit, that seems to have fixed it for me. Thank you for pointing out that it was failing!

If the issue is resolved and there are no other problems I will close this issue

**Comment by Demian101** [comment]
It works ! thanks a lot 😆

**Comment by EDGDrummond** [comment]
fyi keccak doesn't work, but that fix will take far longer than it is worth
